export const membersData = [
  {
    email: "valkyrie@arcade.net",
    username: "valkyrie",
    gender: "female",
    dateOfBirth: "1995-04-22",
    name: "Vera",
    created: "2021-03-15",
    lastActive: "2023-11-02",
    description: "Tactical strategist with a soft spot for pixel art. I thrive in turn-based RPGs and love dissecting game mechanics. My current obsession? Modding Fire Emblem maps and writing lore for my custom campaigns.",
    city: "Rotterdam",
    country: "Netherlands",
    image: "/images/f1.jpeg"
  },
  {
    email: "shadowbyte@fragzone.gg",
    username: "shadowbyte",
    gender: "male",
    dateOfBirth: "1990-09-10",
    name: "Dorian",
    created: "2020-07-08",
    lastActive: "2024-05-19",
    description: "Cyberpunk junkie and stealth game purist. I main Dishonored, Deus Ex, and anything with cloaking mechanics. I stream late-night infiltration runs and build immersive UI overlays for my viewers.",
    city: "Calgary",
    country: "Canada",
    image: "/images/m1.jpeg"
  },
  {
    email: "pixelwitch@manaquest.io",
    username: "pixelwitch",
    gender: "female",
    dateOfBirth: "1992-02-14",
    name: "Lilith",
    created: "2018-11-30",
    lastActive: "2023-08-21",
    description: "Indie dev and cosy gamer. Stardew Valley, Spiritfarer, and potion-crafting sims are my jam. I design witchy-themed UI kits and host chill dev streams where we build magical interfaces together.",
    city: "Turriff",
    country: "Scotland",
    image: "/images/f2.jpeg"
  },
  {
    email: "rex@mecharena.org",
    username: "rex",
    gender: "male",
    dateOfBirth: "1985-06-03",
    name: "Rex",
    created: "2019-06-22",
    lastActive: "2024-12-01",
    description: "Mech pilot since the PS2 era. I live for armored warfare and twitch reflexes—Armored Core, Titanfall, and Gundam Versus. I build custom controller rigs and run a Discord for mech sim enthusiasts.",
    city: "Seattle",
    country: "USA",
    image: "/images/m2.jpeg"
  },
  {
    email: "echo@dreamloop.gg",
    username: "echo",
    gender: "female",
    dateOfBirth: "1998-07-30",
    name: "Echo",
    created: "2022-04-10",
    lastActive: "2025-01-17",
    description: "Narrative designer and rhythm game addict. I write branching storylines for visual novels and remix game soundtracks in my spare time. Favourite titles: Celeste, Sayonara Wild Hearts, and Omori.",
    city: "Perth",
    country: "Australia",
    image: "/images/f3.jpeg"
  },
  {
    email: "glitchqueen@respawn.gg",
    username: "glitchqueen",
    gender: "female",
    dateOfBirth: "1994-11-12",
    name: "Tasha",
    created: "2020-02-19",
    lastActive: "2024-10-03",
    description: "Speedrunner and bug hunter. I break games for fun—whether it's clipping through walls in Skyrim or frame-perfect skips in Hollow Knight. I document exploits and run glitch showcases on my channel.",
    city: "Munich",
    country: "Germany",
    image: "/images/f4.jpeg"
  },
  {
    email: "paladin@lootforge.com",
    username: "paladin",
    gender: "male",
    dateOfBirth: "1988-03-27",
    name: "Gareth",
    created: "2017-09-14",
    lastActive: "2023-12-22",
    description: "Tank main and raid leader. I’ve been grinding MMOs since EverQuest and still lead weekly dungeon runs in FFXIV. I write guides for new players and manage a guild with over 300 members.",
    city: "Stafford",
    country: "England",
    image: "/images/m3.jpeg"
  },
  {
    email: "neonfox@arcadia.gg",
    username: "neonfox",
    gender: "female",
    dateOfBirth: "1996-08-05",
    name: "Rina",
    created: "2021-06-11",
    lastActive: "2025-02-09",
    description: "Retro arcade lover and synthwave DJ. I collect CRTs and speedrun classics like Contra and Castlevania. My streams blend gameplay with live music sets and neon-lit overlays.",
    city: "Rochdale",
    country: "UK",
    image: "/images/f5.jpeg"
  },
  {
    email: "drift@trackmania.io",
    username: "drift",
    gender: "male",
    dateOfBirth: "1993-01-19",
    name: "Leo",
    created: "2019-10-05",
    lastActive: "2024-07-30",
    description: "Racer and physics nerd. I build custom tracks in Trackmania and analyse driving mechanics in sim racers. My YouTube channel breaks down drift theory and car tuning for beginners.",
    city: "Milan",
    country: "Italy",
    image: "/images/m4.jpeg"
  },
  {
    email: "oracle@dreamforge.gg",
    username: "oracle",
    gender: "male",
    dateOfBirth: "1990-05-16",
    name: "Sage",
    created: "2018-08-28",
    lastActive: "2025-03-04",
    description: "Lore master and puzzle solver. I dive deep into narrative games like The Witness, Outer Wilds, and Return of the Obra Dinn. I host theorycrafting sessions and write fan essays decoding game symbolism.",
    city: "Cork",
    country: "Ireland",
    image: "/images/m5.jpeg"
  }
]